services:
  db-locadora:
    image: postgres:16-alpine
    container_name: db-locadora
    environment:
      POSTGRES_DB: locadora
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "55432:5432"